on:
  schedule:
    - cron: "* 0,9 * * *"

env:
  DEVELOPER_KEY: ${{ secrets.DEVELOPER_KEY }}
  WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: "3.7"
          architecture: "x64"
      - run: python main.py
